device_id: cpu
seed: 42
epochs: 10000
max_steps: 100
gamma: 0.95
batch_size: 32

inner_steps: 2
inner_lr: 1.0e-3
outer_lr: 1.0e-2

actor_critic:
  hidden_size: 128

a2c:
  value_coeff: 0.5

test: False
